# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='currently_studying',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_lead',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_sub',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skills',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tools',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
