# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0003_auto_20180208_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('email', models.EmailField(default='', max_length=256)),
                ('github', models.CharField(default='', max_length=256)),
                ('linkedin', models.CharField(default='', max_length=256)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
